### ISSUE TITLE
Wish: simulating water/ice/rock propagation (with different water models)

### ISSUE THREAD

**Issue by pkalaczynski** [mceq-project/MCEq#16]
Hi again!

is there any plan on including water/ice/rock propagation? This would be really great for systematic studies for a number of experiments (although my guess is it may not be so simple).

**Comment by afedynitch** [comment]
Hi.

Well, it is actually already there but somewhat unfinished and not fully debugged. There is a density class called GeneralizedTarget. This gives you a 1D target with piece-wise homogeneous media. 
This may be numerically unstable and needs sometimes a bit of fiddling mainly because I have no time to properly debug it. There are even people using this.

To switch to one of these media ['air', 'standard_rock', 'ice', 'water'], look at line 368 in data.py. These are dEdX tables from PDG. I had no time yet to make a user iface. If you think a config variable will do the job, let me know or feel free to propose something. If you compute also hadronic cascades and not just muons, you need to adjust A_target in the config and preferably not deviate much from 14 since the interaction tables are for air (but dependence is relatively weak).

Look at the attached jupyter notebook for how to interact with this feature. You should definitely compare this with some kind of benchmark calculation or a different code, for instance [PROPOSAL](https://github.com/tudo-astroparticlephysics/PROPOSAL.) Please let me know about the results, positive or negative, since I have no idea.
[ArbitraryDensityPrototype.zip](https://github.com/afedynitch/MCEq/files/4343994/ArbitraryDensityPrototype.zip)

**Comment by pkalaczynski** [comment]
Thanks, will have a look!

**Comment by pkalaczynski** [comment]
Hmm, when I execute `ad.draw_materials()` in your jupyter notebook it does not display a plot :< Do I need `%run -i "../../initjupyter_ng.py"` for this?

**Comment by afedynitch** [comment]
That's a remnant of my dev environment. There are just basic settings and imports. Replace it with

    # %run -i "../../initjupyter_ng.py"
    import numpy as np
    %matplotlib inline
    import mceq_config as config
    from MCEq.core import MCEqRun
    import crflux.models as pm
    import matplotlib.pyplot as plt

**Comment by pkalaczynski** [comment]
The notebook works, however by the similar logic as in the muon bundles issue, I drop this for now.

**Comment by pkalaczynski** [comment]
FYI, I've tested this notebook with MCEq `v1.6` and the ratio of muon spectrum to the one at the surface seems not to produce the same result anymore.

plot from your notebook:
![image](https://github.com/mceq-project/MCEq/assets/25057504/48533fa5-7d20-4b46-952b-4b049b774b51)

what I get running the same code:
![image](https://github.com/mceq-project/MCEq/assets/25057504/355b212a-b4bb-4940-a1b2-edbf7bc79d40)

**Comment by afedynitch** [comment]
Hi! Could you please share some pieces of your code? What are we looking at here?

**Comment by pkalaczynski** [comment]
Ah, tried now to reproduce from scratch from your `ArbitraryDensityPrototype.ipynb` notebook and when I just add missing imports I do get the same plot, must have modified something else when playing with things. Sorry for the false alarm 🙈. I wanted to try to evaluate muon and neutron fluxes in two underground mines, but I was getting strange results... I might produce a comparison with something else at some point as a cross-check, will post it here for reference.

**Comment by afedynitch** [comment]
Glad to hear. But good that you mention that you want to compute underground labs. If these labs are deep, i.e. X > 1 kmwe then the MCEq propagation is not going to return accurate results. There are some technical reasons behind it, which are not relevant for X < 100000 g/cm2 but become relevant for larger depth. You may want to consider using the code [MUTE](https://github.com/wjwoodley/mute), which makes use of MCEq at the surface and then does some convolutions to calculate the underground or underwater fluxes.

**Comment by pkalaczynski** [comment]
Oh, basically MCEq + PROPOSAL, I see :)

**Comment by pkalaczynski** [comment]
Thanks for the recommendation @afedynitch, MUTE was exactly what I needed :)
